// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx"
import * as $_app from "./routes/_app.tsx"
import * as $contact from "./routes/contact.tsx"
import * as $fee from "./routes/fee.tsx"
import * as $home from "./routes/home.tsx"
import * as $index from "./routes/index.tsx"
import * as $information_i00 from "./routes/information/i00.tsx"
import * as $information_i01 from "./routes/information/i01.tsx"
import * as $policy from "./routes/policy.tsx"
import * as $seminar from "./routes/seminar.tsx"
import * as $seminar_s00 from "./routes/seminar/s00.tsx"
import * as $seminar_s01 from "./routes/seminar/s01.tsx"
import * as $seminar_s02 from "./routes/seminar/s02.tsx"
import * as $service from "./routes/service.tsx"
import * as $staff from "./routes/staff.tsx"
import * as $Carousel from "./islands/Carousel.tsx"
import * as $Header from "./islands/Header.tsx"
import type { Manifest } from "$fresh/server.ts"

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/contact.tsx": $contact,
    "./routes/fee.tsx": $fee,
    "./routes/home.tsx": $home,
    "./routes/index.tsx": $index,
    "./routes/information/i00.tsx": $information_i00,
    "./routes/information/i01.tsx": $information_i01,
    "./routes/policy.tsx": $policy,
    "./routes/seminar.tsx": $seminar,
    "./routes/seminar/s00.tsx": $seminar_s00,
    "./routes/seminar/s01.tsx": $seminar_s01,
    "./routes/seminar/s02.tsx": $seminar_s02,
    "./routes/service.tsx": $service,
    "./routes/staff.tsx": $staff,
  },
  islands: {
    "./islands/Carousel.tsx": $Carousel,
    "./islands/Header.tsx": $Header,
  },
  baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
